# Generated by Django 2.1.7 on 2019-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20190410_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
