# Generated by Django 2.2 on 2019-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20190413_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='artistsName',
            field=models.ManyToManyField(blank=True, to='details.Artist'),
        ),
    ]
